sources:
    - name: graph-test
      handler:
          graphql:
              endpoint: https://api.studio.thegraph.com/query/65471/graph-test/version/latest

documents:
    - ../../graphql/pairs.graphql
    - ../../graphql/meta.graphql
